wiseconnect: Patch usage of sl_strnlen() to fix warnings
The compiler complains:

    .../sl_utility.c: In function 'convert_string_to_mac_address':
    .../sl_utility.c:419:18: error: passing argument 1 of 'sl_strnlen'
                             discards 'const' qualifier from pointer
                             target type [-Werror=discarded-qualifiers]
      419 |   if (sl_strnlen(line, 18) != 17) {
          |                  ^~~~
    In file included from .../sl_utility.c:34:
    .../sl_string.h:108:25: note: expected 'char *' but argument is of
                            type 'const char *'
      108 | size_t sl_strnlen(char *str, size_t max_len);

This issue is in fact only a mistake in the declaration of sl_strnlen().
Anyway, sl_strnlen() and strnlen() are equivalent and strnlen() does not
suffer of this bug.

Upstream-status: Pending
Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>
(cherry picked from commit 0fc098380540bb7278875ae1fddb41c9c04f6fe7)